packages:
  - apps/*
  - packages/*

catalog:
  "@better-auth/expo": ^1.4.18
  "@cloudflare/workers-types": ^4.20251213.0
  "@trpc/client": ^11.7.2
  "@trpc/server": ^11.7.2
  alchemy: ^0.82.1
  better-auth: ^1.4.18
  dotenv: ^17.2.2
  hono: ^4.8.2
  typescript: ^5
  vitest: ^3.2.4
  zod: ^4.1.13

onlyBuiltDependencies:
  - better-sqlite3
