name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the bug
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Steps to reproduce, expected vs actual behavior
    validations:
      required: true
