name: Refactor
description: Propose a code refactor
labels: [refactor]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the refactor
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: What should change and why
    validations:
      required: true
